### ISSUE TITLE
Issue with folder names in Windows

### ISSUE THREAD

**Issue by Metastasis** [kriskate/dota-data#2]
@kriskate 
In Windows folders can't contain characters like ":". Thus you can't clone this repo under Windows.
Could you change the way how they are generated?
Perhaps it could be something like **"{version}\_{yyyy}\_{mm}\_{dd}\_{hh}\_{min}\_{sec}\_{ms}"**.
Yet it will be harder to parse because now we need to glue date parts together but this format will be compatible with both Linux and Windows worlds.

**Comment by kriskate** [comment]
Woah, didn't think of that.
Unfortunatelly, I switched to storing this data in a firebase instance, but will try to update this repo with the requested format these days.

**Comment by Metastasis** [comment]
Oh, somehow I missed this repo https://github.com/kriskate/dota-backend. I think I will use that.
Also you could encode folder names in base64 (and stick to the current format). This should be even easier. However if you have no plans to maintain current repo I think this issue can be closed.

PS: Many thanks for you work! It's really helpful! :)

**Comment by kriskate** [comment]
I've actually been having a rename in the works but because of the firebase switch I didn't finish it. 
But it's now here, and for the moment, at least, I'll be keeping this repo up-to-date.

https://github.com/kriskate/dota-data/tree/master/2018-10-03_20-13-59_31

The root file (info.json) now also contains the current version folder's name.
